# Generated by Django 4.1.1 on 2022-10-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QUIZ_APP', '0002_quiz_quiz_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choice',
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
