# Generated by Django 4.1.1 on 2022-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QUIZ_APP', '0004_delete_quiz_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('log_in', models.DateField(max_length=50)),
                ('reg_time', models.DateField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
